name: Basic Console App build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildwindows:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      -
        name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules : true
      -
       # I wish I could use Chocolatey or something else but it's a pain in the but
        name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.1'
      -
        name: Install SPackager
        uses: Skarsnik/sqpackager-action@main
      -
        name: build
        id: build
        run: | 
              $pwd
              cd basic-console-app
              SQPackager --build windows
      -
        name: print output
        run: |
              echo "Standalone zip : ${{steps.build.outputs.sqpackager_win32_x64_standalone_zip}}"
              echo "Standalone 7zip : ${{steps.build.outputs.sqpackager_win32_x64_standalone_7zip}}"
              echo "Innosetup Installer : ${{steps.build.outputs.sqpackager_win32_x64_innosetup}}"
  builddebian:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules : true
      -
        name: Install SPackager
        uses: Skarsnik/sqpackager-action@main
      -
        name: build
        id: build
        run: |
              sudo SQPackager --prepare debian
              cd basic-console-app
              SQPackager --gen-debian --build debian
      -
        name: print output
        run: |
              echo "Debian Package : ${{steps.build.outputs.sqpackager_amd64_deb}}"

